#!/bin/sh
#
# Unix shell script to run UMLGraph on the specified base file name
# For this to work the JDK tools.jar file must be located in the
# same directory as UmlGraph.jar.  You also need to adjust the path
# of UmlGraph.jar to the actual path where the jar file is installed.
#
# $Id$
#

if [ x$2 = x ]
then
	echo usage: umlgraph base_file_name filetype [umlgraph arguments] 1>&2
	echo example: umlgraph MyClass png 1>&2
	echo '(The above will convert MyClass.java into MyClass.png)' 1>&2
	exit 1
else
	java -jar lib/UmlGraph.jar -package $* -output - $1.java |
	dot -T$2 -o$1.$2
fi
